### ISSUE TITLE
Discovered an insignificant bug

### ISSUE THREAD

**Issue by ptrpetro** [ado21/DynamicMacros#16]
Could be related to CheckPvPLink addon

2x [ADDON_ACTION_FORBIDDEN] AddOn 'DynamicMacros' tried to call the protected function 'CopyToClipboard()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CopyToClipboard'
[string "@Blizzard_UnitPopupShared/UnitPopupSharedButtonMixins.lua"]:1134: in function `OnClick'
[string "@Blizzard_UnitPopupShared/UnitPopupShared.lua"]:151: in function `func'
[string "@Blizzard_SharedXML/Mainline/UIDropDownMenu.lua"]:1019: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:133_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:133_OnClick"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by Vexali0n** [comment]
There is some kind of taint. Impossible to figure out why with this log because addon is not calling any copytoclipboard functions.

Additionaly afaik this can be tainted by different addon and buggrabber just picked up next addon in line which used the variable which was tainted already

What is the specific situation which triggered it? 

How did you consider this is related to checkpvp addon ?

I need to simulate it.

**Comment by Vexali0n** [comment]
Additionally if you type this into game chat "/console taintLog 2" it will enable to log the taint with more information. Once that error you mentioned happens again you can send me `taint.log` which is found inside your `World of Warcraft/_retail_/Logs` folder

**Comment by Vexali0n** [comment]
additional information was not provided therefore closed
