### ISSUE TITLE
alt modifier seems not to work in single macro

### ISSUE THREAD

**Issue by chris251190** [ado21/DynamicMacros#18]
When I want to use the macro that is specified in the Readme, but replace ctrl with alt the macro does not seem to work for the alt-Modifier.

Working:

#showtooltip
/cast [nomod,@Krionel]Regrowth
/cast [mod:shift,@dynamicMacros,exists][mod:shift,@target]Regrowth
/cast [mod:ctrl,@dynamicMacros,exists][mod:ctrl,@focus]Regrowth

Not working:

#showtooltip
/cast [nomod,@Krionel]Regrowth
/cast [mod:shift,@dynamicMacros,exists][mod:shift,@target]Regrowth
/cast [mod:alt,@dynamicMacros,exists][mod:alt,@focus]Regrowth

Do you have the same issue?

Thanks in advance.

Best regards

**Comment by chris251190** [comment]
ok the issue was that the Self Cast was set to "Auto" and needs to be set to "None". Then it's not an issue, but could be mentioned in the ReadMe in case you want to address this issue in the documentation.

![self cast](https://github.com/user-attachments/assets/bdc2f7a0-b053-45ac-ab00-2248b6d93666)

**Comment by Vexali0n** [comment]
I have self cast set to Auto and alt modifier works. Only thing I can think of is you have "alt + your key" bound by default from blizzard and now it does not take your "alt + key". 

Simply quick bind your alt + key via Edit Mode to any action bar, save it and unbind it. That will free that bind.

Either way this is not addon bug.
