### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by KingGlyph** [ado21/DynamicMacros#2]
When having damager macro e.g.

/cast [@damager] Intervene or /cast [@'..D..'] Intervene

This will be replaced to /cast @'..H..' Intervene, even when the player assigned is a damage dealer.

Additionally, if healer loads in first all macros will be replaced with healer name, if the damage dealer loads in second the code won't trigger to replace '..D..' with the damage dealer name, as it's already been changed to '..H..' and replaced with healer name.

![image](https://user-images.githubusercontent.com/104679793/216221895-607c51ec-6d7d-4ed7-a8ed-83f01660f16c.png)

![image](https://user-images.githubusercontent.com/104679793/216221913-70d7742a-73b8-49e7-a671-0e16018c385e.png)
![image](https://user-images.githubusercontent.com/104679793/216221915-34729421-11a7-4e76-8f78-45e4536155ee.png)

**Comment by Vexali0n** [comment]
That is clearly not how addon works. Please read through documentation carefully. You used it completely wrong. 

**Intervene for healer only:**
#showtooltip
/cast [@healer] Intervene

**Intervene for damager only:**
#showtooltip
/cast [@healer]
/cast [@damager] Intervene

**Both in one macro:**
#showtooltip
/cast [nomod,@healer] Intervene
/cast [mod:shift,@damager] Intervene

Additional hint: After entering arena wait like 3 seconds after all of your teammates joined into arena. After that you can open your macro window to verify results.

Everything is mentioned in documentation.

**Comment by KingGlyph** [comment]
I had an epiphany after I wrote the issue of how to make it work. Good to go.

Great addon btw, appreciate you.

**Comment by Vexali0n** [comment]
Glad you made it work.
