### ISSUE TITLE
Enhancement: Enemy DPS1/DPS2/Healer?

### ISSUE THREAD

**Issue by rjacqu** [ado21/DynamicMacros#5]
Curious about if the potential of getting enemy macros working? Normally would always just use arena1/2/3 but in some scenarios I would only like 2 keybinds for say; disarming dps classes. In that scenario macros for enemydps1 or enemydps2 would we awesome.. Is that possible from your understanding of what data blizzard lets us access?

**Comment by Vexali0n** [comment]
Question is how would you distinguish which of the DPS is supposed to be "enemydps1" or "enemydps2". To make it clear addons are unable to shuffle numbers around which blizzard assigned to them. So for example if healer is assigned as party member 2 there is no way to make him member 1 or 3.

In case you are going to point to SortGroup addon it just visually order party frames based on numbers blizzard assigned to players.

Even my addon is unable to work for healer players. I just found a way how to separate it by a big workaround if you are one of DPS players.

**Comment by rjacqu** [comment]
i see. yes i was facing similar limitations was curious on your thoughts!
